✨(api) add indicator persistence mixins
We need a generic way to cache indicators calculation so that we can
speed up API responses. Caching indicator results should be performed
asynchronously or pre-calculated periodically (as cron jobs).

Our proposition relies on indicators mixins that can be added to
standard indicators to add cache support. We distinguish two types of
cache: a dummy cache for metrics that mostly rely on a single result
that cannot be aggregated periodically, and an incremental cache for
indicators that can be computed on a defined time span and aggregated on
a larger time span.

diff --git a/bin/pytest b/bin/pytest
--- a/bin/pytest
+++ b/bin/pytest
@@ -1,9 +1,25 @@
 #!/usr/bin/env bash
 
+set -eo pipefail
+
+declare -r API_SERVICE="api"
+declare -r APP_SERVICE="app"
+declare -r SERVICE="${PYTEST_SERVICE:-${API_SERVICE}}"
+declare -a ALLOWED_SERVICES=("${APP_SERVICE}" "${API_SERVICE}")
+declare -A CONFIGURATION
+CONFIGURATION[${API_SERVICE}]="core/pyproject.toml"
+CONFIGURATION[${APP_SERVICE}]="pyproject.toml"
 declare DOCKER_USER
 DOCKER_USER="$(id -u):$(id -g)"
 
+if [[ ! "${ALLOWED_SERVICES[*]}" =~ "${SERVICE}" ]]; then
+    echo "Unknown service ${SERVICE}. Abort."
+    exit 1
+fi
+
+echo "Will run pytest for ${SERVICE} service with ${CONFIGURATION[${SERVICE}]} configuration..."
+
 DOCKER_USER=${DOCKER_USER} docker compose run \
   --rm \
-  api \
-  pytest -c core/pyproject.toml "$@"
+  "${SERVICE}" \
+  pytest -c "${CONFIGURATION[${SERVICE}]}" "$@"
